version: "3.4"

services:
  b2bgsm:
    image: ${IMG}
    command: npm start
    ports:
      - 8586:3000
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_BASE_URL: -https://strapi.garamaleki.ir/graphql/
